<?php

declare(strict_types=1);

return [
    'routes' => [
        ['name' => 'api#capabilities', 'url' => '/api/v1/capabilities', 'verb' => 'GET'],
        ['name' => 'api#bindings', 'url' => '/api/v1/bindings', 'verb' => 'GET'],
        [
            'name' => 'api#manifest',
            'url' => '/api/v1/bindings/{id}/manifest',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'api#content',
            'url' => '/api/v1/bindings/{id}/files/{fileId}/content',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+', 'fileId' => '[1-9][0-9]*'],
        ],
        [
            'name' => 'changes#index',
            'url' => '/api/v1/bindings/{id}/changes',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'authorization#authorize',
            'url' => '/api/v1/bindings/{id}/authorize',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        ['name' => 'identity_admin#index', 'url' => '/api/v1/admin/identities', 'verb' => 'GET'],
        ['name' => 'diagnostics#index', 'url' => '/api/v1/admin/diagnostics', 'verb' => 'GET'],
        ['name' => 'identity_admin#create', 'url' => '/api/v1/admin/identities', 'verb' => 'POST'],
        ['name' => 'identity_admin#revoke', 'url' => '/api/v1/admin/identities/revoke', 'verb' => 'POST'],
        [
            'name' => 'employee_file_status#show',
            'url' => '/api/v1/files/{fileId}/status',
            'verb' => 'GET',
            'requirements' => ['fileId' => '[1-9][0-9]*'],
        ],
        [
            'name' => 'publication#state',
            'url' => '/api/v1/admin/bindings/{id}/files/{fileId}/publication',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+', 'fileId' => '[1-9][0-9]*'],
        ],
        ['name' => 'binding_admin#index', 'url' => '/api/v1/admin/bindings', 'verb' => 'GET'],
        ['name' => 'binding_admin#save', 'url' => '/api/v1/admin/bindings', 'verb' => 'POST'],
        [
            'name' => 'source_pairing#show',
            'url' => '/api/v1/admin/bindings/{id}/source-pairing',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#prepare',
            'url' => '/api/v1/admin/bindings/{id}/source-pairing',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#abort',
            'url' => '/api/v1/admin/bindings/{id}/source-pairing',
            'verb' => 'DELETE',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#commit',
            'url' => '/api/v1/bindings/{id}/source-pairing/commit',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#rotationStatus',
            'url' => '/api/v1/admin/bindings/{id}/source-pairing/rotation',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#prepareRotation',
            'url' => '/api/v1/admin/bindings/{id}/source-pairing/rotation',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#abortRotation',
            'url' => '/api/v1/admin/bindings/{id}/source-pairing/rotation',
            'verb' => 'DELETE',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#commitRotation',
            'url' => '/api/v1/bindings/{id}/source-pairing/rotation/commit',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#finalizeRotation',
            'url' => '/api/v1/bindings/{id}/source-pairing/rotation/finalize',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'source_pairing#abortRotationMachine',
            'url' => '/api/v1/bindings/{id}/source-pairing/rotation/abort',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'binding_admin#stop',
            'url' => '/api/v1/admin/bindings/{id}/stop',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'binding_admin#resume',
            'url' => '/api/v1/admin/bindings/{id}/resume',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'binding_admin#remove',
            'url' => '/api/v1/admin/bindings/{id}',
            'verb' => 'DELETE',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'machine_key_admin#index',
            'url' => '/api/v1/admin/bindings/{id}/keys',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'machine_key_admin#issue',
            'url' => '/api/v1/admin/bindings/{id}/keys',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'machine_key_admin#revoke',
            'url' => '/api/v1/admin/bindings/{id}/keys/{keyId}',
            'verb' => 'DELETE',
            'requirements' => ['id' => '[A-Za-z0-9_-]+', 'keyId' => '[A-Za-z0-9._-]+'],
        ],
        [
            'name' => 'event_connection_admin#show',
            'url' => '/api/v1/admin/bindings/{id}/event-connection',
            'verb' => 'GET',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'event_connection_admin#configure',
            'url' => '/api/v1/admin/bindings/{id}/event-connection',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'event_connection_admin#revoke',
            'url' => '/api/v1/admin/bindings/{id}/event-connection',
            'verb' => 'DELETE',
            'requirements' => ['id' => '[A-Za-z0-9_-]+'],
        ],
        [
            'name' => 'publication#withdraw',
            'url' => '/api/v1/admin/bindings/{id}/files/{fileId}/withdraw',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+', 'fileId' => '[1-9][0-9]*'],
        ],
        [
            'name' => 'publication#republish',
            'url' => '/api/v1/admin/bindings/{id}/files/{fileId}/republish',
            'verb' => 'POST',
            'requirements' => ['id' => '[A-Za-z0-9_-]+', 'fileId' => '[1-9][0-9]*'],
        ],
    ],
];
